version: 3

tasks:
  copy-pkgs:
    desc: Copies packages from node_modules to the static folder
    cmds:
      - mkdir -p static/pkgs
      - cp node_modules/localforage/dist/localforage.min.js static/pkgs/localforage.js
      - cp node_modules/blissfuljs/bliss.min.js static/pkgs/bliss.js
  serve:
    desc: Serves the site on localhost
    cmds:
      - npx eleventy --serve --quiet
  serve-python:
    desc: Serves the site on localhost with Python. Useful after building with a post-build cleanup.
    cmds:
      - python -m http.server 8080 -d _site
  build-noclean:
    desc: Builds the site without removing the contents of the `_site` directory
    cmds:
      - npx eleventy --quiet
  clean:
    desc: Deletes the `_site` directory to ensure a clean build
    cmds:
      - rm -r _site
  post-build:
    desc: Operations after building
    dir: _site
    cmds:
      - rm -r pkgs
      - rm script.js
      - rm *.njk
  build-no-post:
    desc: Builds the site clean, with no post-build cleanup
    cmds:
      - task: clean
      - task: build-noclean
  build:
    desc: Builds the site clean
    cmds:
      - task: build-no-post
      - task: post-build
  publish:
    desc: Publishes the site on Neocities
    cmds:
      - neocities push
  build-publish:
    desc: Builds and publishes the site
    cmds:
      - task: build
      - task: publish